<a href="https://colab.research.google.com/github/janeeeeverdad/Verdad/blob/main/Exer5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSST 104

**Verdad, Jane Benneth Dione**

**BSCS-3B**

**February 28, 2024**

**MULTIPLE LINEAR REGRESSION**

# 1. Import Libraries

In [ ]:
import pandas as pd #Data Manipulation
import numpy as np #Mathematical Operation
import matplotlib.pyplot as plt #Data Visualization
from sklearn.model_selection import train_test_split #Data Modelling/Training Data
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


# 2.  Creating a Synthetic Dataset

In [ ]:
np.random.seed() #For Reproducibility
X = np.random.rand(100, 3) #
y =  X[:,0] * 150000 + X[:,1] *10000 + X[:,2] * 50000 + 50000

# 3. Converting to DataFrame

In [ ]:
data = pd.DataFrame(X, columns=('Size', 'Bedrooms', 'Age'))
data ['Price'] = y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=42)
data.head()

Size  Bedrooms       Age          Price
0  0.100997  0.182896  0.425361   88246.590689
1  0.721826  0.197987  0.329123  176709.946587
2  0.690666  0.860854  0.819048  203160.846322
3  0.125095  0.801633  0.865935  120077.347675
4  0.550498  0.195066  0.051050  137077.843821

# 4. Initializing the Model

In [ ]:
model = LinearRegression()


# 5. Fitting the Model

In [ ]:
model.fit (X_train,y_train)

LinearRegression()

# 6. Making Predictions

In [ ]:
y_predict = model.predict(X_test)
print(X_test)
print(y_predict)

[[0.76873813 0.27304382 0.98748237]
 [0.85485881 0.21417072 0.32533476]
 [0.79493888 0.22504523 0.69286431]
 [0.06627275 0.92120999 0.61598487]
 [0.94846804 0.70301187 0.35021809]
 [0.33470898 0.51622407 0.33868649]
 [0.1305231  0.19569964 0.1894042 ]
 [0.53123798 0.84212895 0.50076557]
 [0.68176806 0.83845654 0.42286159]
 [0.60227653 0.85053583 0.19890466]
 [0.81746675 0.32858045 0.7217328 ]
 [0.18085968 0.57886521 0.31219421]
 [0.29589829 0.69029458 0.549096  ]
 [0.63000007 0.59058252 0.52761727]
 [0.73688421 0.31332214 0.59382078]
 [0.79884617 0.44992489 0.19852422]
 [0.73211186 0.23164035 0.32891763]
 [0.71138245 0.37772942 0.3168637 ]
 [0.22144944 0.40517964 0.61272299]
 [0.9316166  0.79552609 0.96311077]]
[217415.2755704  196637.26705094 206134.49926476  99952.25549634
 216811.22975455 122302.91177107  81005.67105878 163145.2646078
 181792.85366866 158792.07076031 211992.45787262  98527.31416663
 128742.48876705 176786.69845931 193356.89152469 184252.38585647
 178579.06387815 176

# 7. Calculating the Mean Squared Error

In [ ]:
mse = mean_squared_error(y_test, y_predict)
print (f"Mean Squared Error:  {mse}")

Mean Squared Error:  3001875031.570999


# 8. Predicting the Price of a new House


In [ ]:
new_house = [[0.5, 2, 10]]
predicted_price = model.predict(new_house)
print (f"Predicted Price: {predicted_price[0]}")

Predicted Price: 644999.9999999999
